packages:
  github.com/dailoi280702/vrs-general-service/repository/user:
    config:
      outpkg: "mockuser"
      dir: "mock/user"
    interfaces:
      I:
  github.com/dailoi280702/vrs-general-service/repository/video:
    config:
      outpkg: "mockvideo"
      dir: "mock/video"
    interfaces:
      I:
  github.com/dailoi280702/vrs-general-service/proto:
    config:
      outpkg: "mockservice"
      dir: "mock/service"
    interfaces:
      ServiceClient:
